const photoData = [
    { src: 'images/mk.webp', cat: 'info', title: 'Author', date: '2025' },
    { src: 'images/gear.webp', cat: 'info', title: 'Equipment', date: '2026' },


    { src: 'images/17.webp', cat: 'happiness', title: 'Sauna roof', date: '2025' },
    { src: 'images/110.webp', cat: 'happiness', title: 'Finland', date: '2018' },
    { src: 'images/91.webp', cat: 'sadness', title: 'Waiting', date: '2011' },
    { src: 'images/09.webp', cat: 'sadness', title: 'Drawing fire', date: '2025' },
    { src: 'images/16.webp', cat: 'sadness', title: 'Done biking', date: '2025' },
    { src: 'images/53.webp', cat: 'sadness', title: 'My way back home', date: '2011' },

    { src: 'images/52.webp', cat: 'sadness', title: 'My friend is gone', date: '2013' },
    { src: 'images/117.webp', cat: 'sadness', title: 'Mama', date: '2026' },
    { src: 'images/22.webp', cat: 'anger', title: 'Not together', date: '2025' },
    { src: 'images/47.webp', cat: 'happiness', title: 'You gotta see this!', date: '2025' },
    { src: 'images/115.webp', cat: 'anger', title: 'Kiddo', date: '2014' },
    { src: 'images/76.webp', cat: 'surprise', title: 'My neighbour about to have a smoke', date: '2025' },
    { src: 'images/104.webp', cat: 'sadness', title: 'Kid', date: '2014' },
    { src: 'images/50.webp', cat: 'surprise', title: 'Red coat', date: '2025' },
    { src: 'images/95.webp', cat: 'fear', title: 'Hesitation', date: '2013' },
    { src: 'images/92.webp', cat: 'fear', title: 'Beaten Cat', date: '2013' },
    { src: 'images/10.webp', cat: 'fear', title: 'Hats for sale', date: '2025' },
  
    { src: 'images/107.webp', cat: 'surprise', title: 'A break', date: '2014' },
    { src: 'images/108.webp', cat: 'surprise', title: 'Lamps', date: '2014' },
    { src: 'images/23.webp', cat: 'surprise', title: 'Snow hats', date: '2025' },
    { src: 'images/65.webp', cat: 'anger', title: 'The burden', date: '2026' },
    { src: 'images/109.webp', cat: 'disgust', title: 'Dead Bicycle', date: '2014' },


    // ... EXTRAT ...
    { src: 'images/74.webp', cat: 'extras', title: 'Orb', date: '2026' },
    { src: 'images/75.webp', cat: 'extras', title: 'Birdie', date: '2025' },
    { src: 'images/77.webp', cat: 'extras', title: 'Azores', date: '2011' },
    { src: 'images/97.webp', cat: 'extras', title: 'Dad is gone', date: '1997' },
    { src: 'images/81.webp', cat: 'extras', title: 'Melanie', date: '2025' },
    { src: 'images/84.webp', cat: 'extras', title: 'Winter comes', date: '2025' },
    { src: 'images/85.webp', cat: 'extras', title: 'I chose this place', date: '2025' },
    { src: 'images/89.webp', cat: 'extras', title: 'Autumn', date: '2011' },
    { src: 'images/91.webp', cat: 'extras', title: 'Waiting', date: '2011' },
    { src: 'images/104.webp', cat: 'extras', title: 'Kid', date: '2014' },
    { src: 'images/106.webp', cat: 'extras', title: 'Remembering', date: '2013' },
    { src: 'images/111.webp', cat: 'extras', title: 'Stairs', date: '2014' },
    { src: 'images/117.webp', cat: 'extras', title: 'Mama', date: '2026' },
    { src: 'images/121.webp', cat: 'extras', title: 'Heavy Xmas', date: '2025' },
    { src: 'images/122.webp', cat: 'extras', title: 'Jasper', date: '2025' },
    { src: 'images/126.webp', cat: 'extras', title: 'Smoker Dude', date: '2026' },
    { src: 'images/128.webp', cat: 'extras', title: 'At the Bus stop', date: '2026' },
    { src: 'images/131.webp', cat: 'extras', title: 'Helping Hand', date: '2025' },
    { src: 'images/119.webp', cat: 'extras', title: 'Tight spots', date: '2025' },
];