const photoData = [
    { src: 'images/mk.webp', cat: 'info', title: 'Author', date: '2025' },
    { src: 'images/gear.webp', cat: 'info', title: 'Equipment', date: '2026' },

    { src: 'images/116.webp', cat: 'happiness', title: 'I ate it all!', date: '2016' },
    { src: 'images/31.webp', cat: 'happiness', title: 'Funny bunny', date: '2016' },
    { src: 'images/01.webp', cat: 'happiness', title: 'Legs', date: '2025' },
    { src: 'images/47.webp', cat: 'happiness', title: 'You gotta see this!', date: '2025' },
    { src: 'images/113.webp', cat: 'happiness', title: 'Get together', date: '2014' },
    { src: 'images/68.webp', cat: 'happiness', title: 'Australian Open', date: '2026' },
    { src: 'images/14.webp', cat: 'happiness', title: 'Air balloons of Xmas', date: '2025' },
    { src: 'images/17.webp', cat: 'happiness', title: 'Sauna roof', date: '2025' },
    { src: 'images/58.webp', cat: 'happiness', title: 'Winter sky', date: '2026' },
    { src: 'images/64.webp', cat: 'happiness', title: 'Lumps', date: '2026' },
    { src: 'images/88.webp', cat: 'happiness', title: 'Mimosa', date: '1998' },
    { src: 'images/96.webp', cat: 'happiness', title: 'Summer evening', date: '2018' },
    { src: 'images/110.webp', cat: 'happiness', title: 'Finland', date: '2018' },

    { src: 'images/104.webp', cat: 'sadness', title: 'Kid', date: '2014' },
    { src: 'images/117.webp', cat: 'sadness', title: 'Mama', date: '2026' },
    { src: 'images/81.webp', cat: 'sadness', title: 'Melanie', date: '2025' },
    { src: 'images/91.webp', cat: 'sadness', title: 'Waiting', date: '2011' },
    { src: 'images/44.webp', cat: 'sadness', title: 'Lack of presence', date: '2025' },
    { src: 'images/52.webp', cat: 'sadness', title: 'My friend is gone', date: '2013' },
    { src: 'images/09.webp', cat: 'sadness', title: 'Drawing fire', date: '2025' },
    { src: 'images/16.webp', cat: 'sadness', title: 'Done biking', date: '2025' },
    { src: 'images/53.webp', cat: 'sadness', title: 'My way back home', date: '2011' },
    { src: 'images/85.webp', cat: 'sadness', title: 'I chose this place', date: '2025' },
    { src: 'images/84.webp', cat: 'sadness', title: 'Winter comes', date: '2025' },
    { src: 'images/111.webp', cat: 'sadness', title: 'Stairs', date: '2014' },

    { src: 'images/115.webp', cat: 'anger', title: 'Kiddo', date: '2014' },
    { src: 'images/22.webp', cat: 'anger', title: 'Not together', date: '2025' },
    { src: 'images/98.webp', cat: 'anger', title: 'Smoker', date: '1997' },
    { src: 'images/42.webp', cat: 'anger', title: 'Smoke', date: '2025' },
    { src: 'images/90.webp', cat: 'anger', title: 'Lines', date: '2011' },
    { src: 'images/65.webp', cat: 'anger', title: 'The burden', date: '2026' },
    { src: 'images/62.webp', cat: 'anger', title: 'Hellhole', date: '2026' },
    { src: 'images/05.webp', cat: 'anger', title: 'Frost', date: '2026' },
    { src: 'images/15.webp', cat: 'anger', title: 'Winter takes over', date: '2025' },

    { src: 'images/95.webp', cat: 'fear', title: 'Hesitation', date: '2013' },
    { src: 'images/103.webp', cat: 'fear', title: 'Always fight or flight', date: '2010' },
    { src: 'images/28.webp', cat: 'fear', title: 'All by myself', date: '2026' },
    { src: 'images/92.webp', cat: 'fear', title: 'Poor Touhu', date: '2013' },
    { src: 'images/38.webp', cat: 'fear', title: 'Devil was here', date: '2026' },
    { src: 'images/10.webp', cat: 'fear', title: 'Hats for sale', date: '2025' },
    { src: 'images/101.webp', cat: 'fear', title: 'Shopping experience', date: '2011' },
    { src: 'images/100.webp', cat: 'fear', title: 'Trust?', date: '2011' },

    { src: 'images/76.webp', cat: 'surprise', title: 'My neighbour about to have a smoke', date: '2025' },
    { src: 'images/50.webp', cat: 'surprise', title: 'Red coat', date: '2025' },
    { src: 'images/107.webp', cat: 'surprise', title: 'A break', date: '2014' },
    { src: 'images/87.webp', cat: 'surprise', title: 'Uncle and Dad', date: '1997' },
    { src: 'images/23.webp', cat: 'surprise', title: 'Snow hats', date: '2025' },
    { src: 'images/82.webp', cat: 'surprise', title: 'Speedster', date: '2025' },
    { src: 'images/99.webp', cat: 'surprise', title: 'Cool babe', date: '2009' },
    { src: 'images/54.webp', cat: 'surprise', title: 'Rhythm', date: '2011' },
    { src: 'images/108.webp', cat: 'surprise', title: 'Lamps', date: '2014' },

    { src: 'images/109.webp', cat: 'disgust', title: 'Done biking', date: '2014' },
    { src: 'images/19.webp', cat: 'disgust', title: 'Life sucked out', date: '2025' },
    { src: 'images/40.webp', cat: 'disgust', title: 'Too many elements', date: '2025' },
    { src: 'images/105.webp', cat: 'disgust', title: 'Midsummers Eve', date: '2014' },
];