const photoData = [
    { src: 'images/mk.webp', cat: 'info', title: 'Author', date: '2025' },
   // { src: 'images/gear.webp', cat: 'info', title: 'Equipment', date: '2026' },

    { src: 'images/17.webp', cat: 'curated', title: 'Sauna roof', date: '2025', description: 'Löyly - public sauna in Helsinki. There was a smiling woman on the roof.',exif: "Canon 5D Mark IV | f/4.0 | 1/500 | ISO 200" },
    { src: 'images/117.webp', cat: 'curated', title: 'Mama', date: '2026' },

    { src: 'images/163.webp', cat: 'curated', title: 'Two Different Worlds', date: '2026', exif: 'Canon EOS R6 Mark III | f/4.0 | 1/800 | ISO 100' },
    { src: 'images/144.webp', cat: 'curated', title: 'The Gap', date: '2026' },

    { src: 'images/110.webp', cat: 'curated', title: 'Finland', date: '2018' },
    { src: 'images/148.webp', cat: 'curated', title: 'Good Life', date: '2026' },
    { src: 'images/145.webp', cat: 'curated', title: 'The Path', date: '2026' },

    { src: 'images/126.webp', cat: 'curated', title: 'Smoker Dude', date: '2026' },
    { src: 'images/162.webp', cat: 'curated', title: 'Invisible Man', date: '2026', description: 'When noboby sees you in a busy street.', exif: 'Canon EOS R6 Mark III | f/4.0 | 1/1000 | ISO 100' },

    { src: 'images/127.webp', cat: 'curated', title: 'Entering', date: '2026' },
    { src: 'images/76.webp', cat: 'curated', title: 'My neighbour about to have a smoke', date: '2025' },

    { src: 'images/16.webp', cat: 'curated', title: 'Done biking', date: '2025' },
    { src: 'images/95.webp', cat: 'curated', title: 'Hesitation', date: '2013' },

    { src: 'images/50.webp', cat: 'curated', title: 'Red coat', date: '2025' },
    { src: 'images/147.webp', cat: 'curated', title: 'Time Passing By', date: '2026' },

    { src: 'images/53.webp', cat: 'curated', title: 'My way back home', date: '2011' },
    { src: 'images/52.webp', cat: 'curated', title: 'My friend is gone', date: '2013' },

   
    { src: 'images/01.webp', cat: 'extras', title: 'Legs', date: '2025' },
    { src: 'images/02.webp', cat: 'extras', title: 'Espa lights', date: '2025' },
    { src: 'images/03.webp', cat: 'extras', title: 'Xmas lights', date: '2025' },
    { src: 'images/04.webp', cat: 'extras', title: 'My TV', date: '2026' },
    { src: 'images/05.webp', cat: 'extras', title: 'Frost', date: '2026' },
    { src: 'images/06.webp', cat: 'extras', title: 'Escape from Winter', date: '2025' },
    { src: 'images/07.webp', cat: 'extras', title: 'Forced growth', date: '2025' },
    { src: 'images/08.webp', cat: 'extras', title: 'Death x2', date: '2025' },
    { src: 'images/09.webp', cat: 'extras', title: 'Drawing fire', date: '2025' },
    { src: 'images/10.webp', cat: 'extras', title: 'Hats for sale', date: '2025' },
    { src: 'images/11.webp', cat: 'extras', title: 'Under the bridge', date: '2025' },
    { src: 'images/12.webp', cat: 'extras', title: 'Isolated life', date: '2025' },
    { src: 'images/13.webp', cat: 'extras', title: 'Tori-gate by accident', date: '2025' },
    { src: 'images/14.webp', cat: 'extras', title: 'Air balloons of Xmas', date: '2025' },
    { src: 'images/15.webp', cat: 'extras', title: 'Winter takes over', date: '2025' },
    { src: 'images/16.webp', cat: 'extras', title: 'Done biking', date: '2025' },
    { src: 'images/17.webp', cat: 'extras', title: 'Sauna roof', date: '2025' },
    { src: 'images/18.webp', cat: 'extras', title: 'Friend or foe?', date: '2025' },
    { src: 'images/19.webp', cat: 'extras', title: 'Life sucked out', date: '2025' },
    { src: 'images/20.webp', cat: 'extras', title: 'Alone', date: '2025' },
    { src: 'images/21.webp', cat: 'extras', title: 'Beauty in my yard', date: '2025' },
    { src: 'images/22.webp', cat: 'extras', title: 'Not together', date: '2025' },
    { src: 'images/23.webp', cat: 'extras', title: 'Snow hats', date: '2025' },
    { src: 'images/24.webp', cat: 'extras', title: 'Always on the toes', date: '2026' },
    { src: 'images/25.webp', cat: 'extras', title: 'Under the bridge 2', date: '2025' },
    { src: 'images/26.webp', cat: 'extras', title: 'Gonna make it!', date: '2025' },
    { src: 'images/27.webp', cat: 'extras', title: 'I told you so!', date: '2025' },
    { src: 'images/28.webp', cat: 'extras', title: 'All by myself', date: '2026' },
    { src: 'images/29.webp', cat: 'extras', title: 'You WILL fit in!', date: '2025' },
    { src: 'images/30.webp', cat: 'extras', title: 'Where materials meet', date: '2025' },
    { src: 'images/31.webp', cat: 'extras', title: 'Funny bunny', date: '2016' },
    { src: 'images/32.webp', cat: 'extras', title: 'Are you not gonna rub me?!', date: '2011' },
    { src: 'images/33.webp', cat: 'extras', title: 'Friend?', date: '2013' },
    { src: 'images/34.webp', cat: 'extras', title: 'That disgusting beautiful seaweed', date: '2025' },
    { src: 'images/35.webp', cat: 'extras', title: 'Blacksmith skills from 1920', date: '2025' },
    { src: 'images/36.webp', cat: 'extras', title: 'End of season', date: '2025' },
    { src: 'images/37.webp', cat: 'extras', title: 'Spiders took over', date: '2025' },
    { src: 'images/38.webp', cat: 'extras', title: 'Devil was here', date: '2026' },
    { src: 'images/39.webp', cat: 'extras', title: 'Jumpy', date: '2025' },
    { src: 'images/40.webp', cat: 'extras', title: 'Too many elements', date: '2025' },
    { src: 'images/41.webp', cat: 'extras', title: 'Idiots went by', date: '2025' },
    { src: 'images/42.webp', cat: 'extras', title: 'Smoke', date: '2025' },
    { src: 'images/43.webp', cat: 'extras', title: 'Money for nothing and chicks for free', date: '2025' },
    { src: 'images/44.webp', cat: 'extras', title: 'Lack of presence', date: '2025' },
    { src: 'images/45.webp', cat: 'extras', title: 'Triple kill?', date: '2025' },
    { src: 'images/46.webp', cat: 'extras', title: 'Consumer Show', date: '2025' },
    { src: 'images/47.webp', cat: 'extras', title: 'You gotta see this!', date: '2025' },
    { src: 'images/48.webp', cat: 'extras', title: 'Is it you, Gilda?', date: '2025' },
    { src: 'images/49.webp', cat: 'extras', title: 'Bag', date: '2025' },
    { src: 'images/50.webp', cat: 'extras', title: 'Red coat', date: '2025' },
    { src: 'images/51.webp', cat: 'extras', title: 'Melanie', date: '2025' },
    { src: 'images/52.webp', cat: 'extras', title: 'My friend is gone', date: '2013' },
    { src: 'images/53.webp', cat: 'extras', title: 'My way back home', date: '2011' },
    { src: 'images/54.webp', cat: 'extras', title: 'Rhythm', date: '2011' },
    { src: 'images/55.webp', cat: 'extras', title: 'Ansku', date: '2010' },
    { src: 'images/56.webp', cat: 'extras', title: 'Abyss', date: '2026' },
    { src: 'images/57.webp', cat: 'extras', title: 'H for extras', date: '2026' },
    { src: 'images/58.webp', cat: 'extras', title: 'Winter sky', date: '2026' },
    { src: 'images/59.webp', cat: 'extras', title: 'Climb!', date: '2026' },
    { src: 'images/60.webp', cat: 'extras', title: 'S for extras', date: '2026' },
    { src: 'images/61.webp', cat: 'extras', title: 'Dunes', date: '2026' },
    { src: 'images/62.webp', cat: 'extras', title: 'Hellhole', date: '2026' },
    { src: 'images/63.webp', cat: 'extras', title: 'Waiting for the summer', date: '2026' },
    { src: 'images/64.webp', cat: 'extras', title: 'Lumps', date: '2026' },
    { src: 'images/65.webp', cat: 'extras', title: 'The burden', date: '2026' },
    { src: 'images/66.webp', cat: 'extras', title: 'Narrowing world view', date: '2026' },
    { src: 'images/67.webp', cat: 'extras', title: 'Winter evening shadows', date: '2026' },
    { src: 'images/68.webp', cat: 'extras', title: 'Australian Open', date: '2026' },
    { src: 'images/69.webp', cat: 'extras', title: 'More winter evening shadows', date: '2026' },
    { src: 'images/70.webp', cat: 'extras', title: 'What are you looking at!', date: '2025' },
    { src: 'images/71.webp', cat: 'extras', title: 'Put your bicycle here in -20°C', date: '2026' },
    { src: 'images/72.webp', cat: 'extras', title: 'Transpfortmation', date: '2026' },
    { src: 'images/73.webp', cat: 'extras', title: 'Forms', date: '2026' },
    { src: 'images/74.webp', cat: 'extras', title: 'Orb', date: '2026' },
    { src: 'images/75.webp', cat: 'extras', title: 'Birdie', date: '2025' },
    { src: 'images/76.webp', cat: 'extras', title: 'Neighbour', date: '2025' },
    { src: 'images/77.webp', cat: 'extras', title: 'Azores', date: '2011' },
    { src: 'images/78.webp', cat: 'extras', title: 'Frosty river', date: '2024' },
    { src: 'images/79.webp', cat: 'extras', title: 'Melanie', date: '2025' },
    { src: 'images/80.webp', cat: 'extras', title: 'Melanie', date: '2025' },
    { src: 'images/81.webp', cat: 'extras', title: 'Melanie', date: '2025' },
    { src: 'images/82.webp', cat: 'extras', title: 'Speedster', date: '2025' },
    { src: 'images/83.webp', cat: 'extras', title: 'Parenting', date: '2026' },
    { src: 'images/84.webp', cat: 'extras', title: 'Winter comes', date: '2025' },
    { src: 'images/85.webp', cat: 'extras', title: 'I chose this place', date: '2025' },
    { src: 'images/86.webp', cat: 'extras', title: 'The new flag of Iceland', date: '2026' },
    { src: 'images/87.webp', cat: 'extras', title: 'Uncle and Dad', date: '1997' },
    { src: 'images/88.webp', cat: 'extras', title: 'Mimosa', date: '1998' },
    { src: 'images/89.webp', cat: 'extras', title: 'Autumn', date: '2011' },
    { src: 'images/90.webp', cat: 'extras', title: 'Lines', date: '2011' },
    { src: 'images/91.webp', cat: 'extras', title: 'Waiting', date: '2011' },
    { src: 'images/92.webp', cat: 'extras', title: 'Poor Touhu', date: '2013' },
    { src: 'images/93.webp', cat: 'extras', title: 'Flower lumps', date: '1996' },
    { src: 'images/94.webp', cat: 'extras', title: 'Paris', date: '2013' },
    { src: 'images/95.webp', cat: 'extras', title: 'Hesitation', date: '2013' },
    { src: 'images/96.webp', cat: 'extras', title: 'Summer evening', date: '2018' },
    { src: 'images/97.webp', cat: 'extras', title: 'Dad is gone', date: '1997' },
    { src: 'images/98.webp', cat: 'extras', title: 'Smoker', date: '1997' },
    { src: 'images/99.webp', cat: 'extras', title: 'Cool babe', date: '2009' },
    { src: 'images/100.webp', cat: 'extras', title: 'Trust?', date: '2011' },
    { src: 'images/101.webp', cat: 'extras', title: 'Shopping experience', date: '2011' },
    { src: 'images/102.webp', cat: 'extras', title: 'Home before the storm', date: '2011' },
    { src: 'images/103.webp', cat: 'extras', title: 'Confusion', date: '2010' },
    { src: 'images/104.webp', cat: 'extras', title: 'Kid', date: '2014' },
    { src: 'images/105.webp', cat: 'extras', title: 'Midsummers Eve', date: '2014' },
    { src: 'images/106.webp', cat: 'extras', title: 'Remembering', date: '2013' },
    { src: 'images/107.webp', cat: 'extras', title: 'Legs', date: '2014' },
    { src: 'images/108.webp', cat: 'extras', title: 'Lamps', date: '2014' },
    { src: 'images/109.webp', cat: 'extras', title: 'Biking', date: '2014' },
    { src: 'images/110.webp', cat: 'extras', title: 'Finland', date: '2018' },
    { src: 'images/111.webp', cat: 'extras', title: 'Stairs', date: '2014' },
    { src: 'images/112.webp', cat: 'extras', title: 'Winter joy', date: '2014' },
    { src: 'images/113.webp', cat: 'extras', title: 'Get together', date: '2014' },
    { src: 'images/114.webp', cat: 'extras', title: 'Gang', date: '2014' },
    { src: 'images/115.webp', cat: 'extras', title: 'Kiddo', date: '2014' },
    { src: 'images/116.webp', cat: 'extras', title: 'I got it all!', date: '2016' },
    { src: 'images/117.webp', cat: 'extras', title: 'Mama', date: '2026' },
    { src: 'images/118.webp', cat: 'extras', title: 'At the airport', date: '2026' },
    { src: 'images/119.webp', cat: 'extras', title: 'Tight spots', date: '2025' },
    { src: 'images/120.webp', cat: 'extras', title: 'Heat', date: '2025' },
    { src: 'images/121.webp', cat: 'extras', title: 'Heavy Xmas', date: '2025' },
    { src: 'images/122.webp', cat: 'extras', title: 'Jasper', date: '2025' },
    { src: 'images/123.webp', cat: 'extras', title: 'Z fence', date: '2026' },
    { src: 'images/124.webp', cat: 'extras', title: 'Winter Cafe', date: '2026' },
    { src: 'images/125.webp', cat: 'extras', title: 'Windows', date: '2026' },
    { src: 'images/126.webp', cat: 'extras', title: 'Smoker Dude', date: '2026' },
    { src: 'images/127.webp', cat: 'extras', title: 'Entering', date: '2026' },
    { src: 'images/128.webp', cat: 'extras', title: 'At the Bus stop', date: '2026' },
    { src: 'images/129.webp', cat: 'extras', title: 'Hat On', date: '2026' },
    { src: 'images/130.webp', cat: 'extras', title: 'Melanie', date: '2025' },
    { src: 'images/131.webp', cat: 'extras', title: 'Helping Hand', date: '2025' },
    { src: 'images/132.webp', cat: 'extras', title: 'Green Line', date: '2025' },
    { src: 'images/133.webp', cat: 'extras', title: 'Twigs', date: '2025' },
    { src: 'images/134.webp', cat: 'extras', title: 'Siva', date: '2026' },
    { src: 'images/135.webp', cat: 'extras', title: 'The Broken One', date: '2026' },
    { src: 'images/136.webp', cat: 'extras', title: 'Red', date: '2026' },
    { src: 'images/137.webp', cat: 'extras', title: 'Face in the Snow', date: '2026' },
    { src: 'images/138.webp', cat: 'extras', title: 'Young Love', date: '2026' },
    { src: 'images/139.webp', cat: 'extras', title: 'Do Not Drop', date: '2026' },
    { src: 'images/140.webp', cat: 'extras', title: 'Comfort', date: '2026' },
    { src: 'images/141.webp', cat: 'extras', title: 'Close', date: '2026' },
    { src: 'images/142.webp', cat: 'extras', title: 'Ready to Play', date: '2026' },
    { src: 'images/143.webp', cat: 'extras', title: 'Filing', date: '2026' },
    { src: 'images/144.webp', cat: 'extras', title: 'The Gap', date: '2026' },
    { src: 'images/145.webp', cat: 'extras', title: 'The Path', date: '2026' },
    { src: 'images/146.webp', cat: 'extras', title: 'Obsessed', date: '2026' },
    { src: 'images/147.webp', cat: 'extras', title: 'Time Passing By', date: '2026' },
    { src: 'images/148.webp', cat: 'extras', title: 'Good Life', date: '2026' },
    { src: 'images/149.webp', cat: 'extras', title: 'The Barber', date: '2026' },
    { src: 'images/150.webp', cat: 'extras', title: 'Home', date: '2026' },
    { src: 'images/151.webp', cat: 'extras', title: 'Broken', date: '2026' },
    { src: 'images/152.webp', cat: 'extras', title: 'Galaxy on Granite', date: '2026' },
    { src: 'images/153.webp', cat: 'extras', title: 'Cuts', date: '2026' },
    { src: 'images/154.webp', cat: 'extras', title: 'Wrinckles', date: '2026' },
    { src: 'images/155.webp', cat: 'extras', title: 'Wavelenghts', date: '2026' },
    { src: 'images/156.webp', cat: 'extras', title: 'Streams', date: '2026' },
    { src: 'images/157.webp', cat: 'extras', title: 'Morning Selfie', date: '2026', exif: 'Canon EOS R6 Mark III | f/5.6 | 1/500 | ISO 1600' },
    { src: 'images/158.webp', cat: 'extras', title: 'Anchoring', date: '2026', exif: 'Canon EOS R6 Mark III | f/4.0 | 1/160 | ISO 100' },
    { src: 'images/159.webp', cat: 'extras', title: 'The Moon at My Balcony', date: '2026', exif: 'Canon EOS R6 Mark III | f/8.0 | 1/500 | ISO 1600' },
    { src: 'images/160.webp', cat: 'extras', title: 'Working Man', date: '2026', exif: 'Canon EOS R6 Mark III | f/5.6 | 1/1000 | ISO 8000' },
    { src: 'images/161.webp', cat: 'extras', title: 'Home', date: '2026', description: 'Weird place for a bird home in Helsinki City??', exif: 'Canon EOS R6 Mark III | f/4.0 | 1/1250 | ISO 250' },
    { src: 'images/162.webp', cat: 'extras', title: 'Invisible Man', date: '2026', description: 'When noboby sees you in a busy street.', exif: 'Canon EOS R6 Mark III | f/4.0 | 1/1000 | ISO 100' },
    { src: 'images/163.webp', cat: 'extras', title: 'Two Different Worlds', date: '2026', exif: 'Canon EOS R6 Mark III | f/4.0 | 1/800 | ISO 100' }
];