const photoData = [
    { src: 'images/mk.jpg', cat: 'info', title: 'Author', date: '2025' },
    { src: 'images/gear.jpg', cat: 'info', title: 'Equipment', date: '2026' },

    { src: 'images/01.jpg', cat: 'happiness', title: 'Legs', date: '2025' },
    { src: 'images/03.jpg', cat: 'happiness', title: 'Xmas lights', date: '2025' },
    { src: 'images/14.jpg', cat: 'happiness', title: 'Air balloons of Xmas', date: '2025' },
    { src: 'images/17.jpg', cat: 'happiness', title: 'Sauna roof', date: '2025' },
    { src: 'images/31.jpg', cat: 'happiness', title: 'Funny bunny', date: '2016' },
    { src: 'images/47.jpg', cat: 'happiness', title: 'You gotta see this!', date: '2025' },
    { src: 'images/51.jpg', cat: 'happiness', title: 'Melanie', date: '2025' },
    { src: 'images/79.jpg', cat: 'happiness', title: 'Melanie', date: '2025' },
    { src: 'images/80.jpg', cat: 'happiness', title: 'Melanie', date: '2025' },
    { src: 'images/57.jpg', cat: 'happiness', title: 'H for happiness', date: '2026' },
    { src: 'images/58.jpg', cat: 'happiness', title: 'Winter sky', date: '2026' },
    { src: 'images/64.jpg', cat: 'happiness', title: 'Lumps', date: '2026' },
    { src: 'images/68.jpg', cat: 'happiness', title: 'Australian Open', date: '2026' },
    { src: 'images/83.jpg', cat: 'happiness', title: 'Parenting', date: '2026' },
    { src: 'images/88.jpg', cat: 'happiness', title: 'Mimosa', date: '1998' },
    { src: 'images/96.jpg', cat: 'happiness', title: 'Summer evening', date: '2018' },
    { src: 'images/110.jpg', cat: 'happiness', title: 'Finland', date: '2018' },
    { src: 'images/113.jpg', cat: 'happiness', title: 'Get together', date: '2014' },
    { src: 'images/116.jpg', cat: 'happiness', title: 'I got it all!', date: '2016' },

    { src: 'images/02.jpg', cat: 'sadness', title: 'Espa lights', date: '2025' },
    { src: 'images/04.jpg', cat: 'sadness', title: 'My TV', date: '2026' },
    { src: 'images/06.jpg', cat: 'sadness', title: 'Escape from Winter', date: '2025' },
    { src: 'images/09.jpg', cat: 'sadness', title: 'Drawing fire', date: '2025' },
    { src: 'images/16.jpg', cat: 'sadness', title: 'Done biking', date: '2025' },
    { src: 'images/20.jpg', cat: 'sadness', title: 'Alone', date: '2025' },
    { src: 'images/32.jpg', cat: 'sadness', title: 'Are you not gonna rub me?!', date: '2011' },
    { src: 'images/36.jpg', cat: 'sadness', title: 'End of season', date: '2025' },
    { src: 'images/44.jpg', cat: 'sadness', title: 'Lack of presence', date: '2025' },
    { src: 'images/49.jpg', cat: 'sadness', title: 'Bag', date: '2025' },
    { src: 'images/52.jpg', cat: 'sadness', title: 'My friend is gone', date: '2013' },
    { src: 'images/53.jpg', cat: 'sadness', title: 'My way back home', date: '2011' },
    { src: 'images/60.jpg', cat: 'sadness', title: 'S for sadness', date: '2026' },
    { src: 'images/61.jpg', cat: 'sadness', title: 'Dunes', date: '2026' },
    { src: 'images/63.jpg', cat: 'sadness', title: 'Waiting for the summer', date: '2026' },
    { src: 'images/74.jpg', cat: 'sadness', title: 'Orb', date: '2026' },
    { src: 'images/75.jpg', cat: 'sadness', title: 'Birdie', date: '2025' },
    { src: 'images/77.jpg', cat: 'sadness', title: 'Azores', date: '2011' },
    { src: 'images/97.jpg', cat: 'sadness', title: 'Dad is gone', date: '1997' },
    { src: 'images/81.jpg', cat: 'sadness', title: 'Melanie', date: '2025' },
    { src: 'images/84.jpg', cat: 'sadness', title: 'Winter comes', date: '2025' },
    { src: 'images/85.jpg', cat: 'sadness', title: 'I chose this place', date: '2025' },
    { src: 'images/89.jpg', cat: 'sadness', title: 'Autumn', date: '2011' },
    { src: 'images/91.jpg', cat: 'sadness', title: 'Waiting', date: '2011' },
    { src: 'images/104.jpg', cat: 'sadness', title: 'Kid', date: '2014' },
    { src: 'images/106.jpg', cat: 'sadness', title: 'Remembering', date: '2013' },
    { src: 'images/111.jpg', cat: 'sadness', title: 'Stairs', date: '2014' },


    { src: 'images/05.jpg', cat: 'anger', title: 'Frost', date: '2026' },
    { src: 'images/86.jpg', cat: 'anger', title: 'The new flag of Iceland', date: '2026' },
    { src: 'images/12.jpg', cat: 'anger', title: 'Isolated life', date: '2025' },
    { src: 'images/15.jpg', cat: 'anger', title: 'Winter takes over', date: '2025' },
    { src: 'images/22.jpg', cat: 'anger', title: 'Not together', date: '2025' },
    { src: 'images/26.jpg', cat: 'anger', title: 'Gonna make it!', date: '2025' },
    { src: 'images/42.jpg', cat: 'anger', title: 'Smoke', date: '2025' },
    { src: 'images/98.jpg', cat: 'anger', title: 'Smoker', date: '1997' },
    { src: 'images/62.jpg', cat: 'anger', title: 'Hellhole', date: '2026' },
    { src: 'images/65.jpg', cat: 'anger', title: 'The burden', date: '2026' },
    { src: 'images/66.jpg', cat: 'anger', title: 'Narrowing world view', date: '2026' },
    { src: 'images/67.jpg', cat: 'anger', title: 'Winter evening shadows', date: '2026' },
    { src: 'images/69.jpg', cat: 'anger', title: 'More winter evening shadows', date: '2026' },
    { src: 'images/73.jpg', cat: 'anger', title: 'Forms', date: '2026' },
    { src: 'images/78.jpg', cat: 'anger', title: 'Frosty river', date: '2024' },
    { src: 'images/90.jpg', cat: 'anger', title: 'Lines', date: '2011' },
    { src: 'images/102.jpg', cat: 'anger', title: 'Home before the storm', date: '2011' },
    { src: 'images/115.jpg', cat: 'anger', title: 'Kiddo', date: '2014' },

    { src: 'images/07.jpg', cat: 'fear', title: 'Forced growth', date: '2025' },
    { src: 'images/08.jpg', cat: 'fear', title: 'Death x2', date: '2025' },
    { src: 'images/10.jpg', cat: 'fear', title: 'Hats for sale', date: '2025' },
    { src: 'images/24.jpg', cat: 'fear', title: 'Always on the toes', date: '2026' },
    { src: 'images/28.jpg', cat: 'fear', title: 'All by myself', date: '2026' },
    { src: 'images/33.jpg', cat: 'fear', title: 'Friend?', date: '2013' },
    { src: 'images/92.jpg', cat: 'fear', title: 'Poor Touhu', date: '2013' },
    { src: 'images/38.jpg', cat: 'fear', title: 'Devil was here', date: '2026' },
    { src: 'images/45.jpg', cat: 'fear', title: 'Triple kill?', date: '2025' },
    { src: 'images/56.jpg', cat: 'fear', title: 'Abyss', date: '2026' },
    { src: 'images/95.jpg', cat: 'fear', title: 'Hesitation', date: '2013' },
    { src: 'images/100.jpg', cat: 'fear', title: 'Trust?', date: '2011' },
    { src: 'images/101.jpg', cat: 'fear', title: 'Shopping experience', date: '2011' },
    { src: 'images/103.jpg', cat: 'fear', title: 'Confusion', date: '2010' },

    { src: 'images/11.jpg', cat: 'surprise', title: 'Under the bridge', date: '2025' },
    { src: 'images/25.jpg', cat: 'surprise', title: 'Under the bridge 2', date: '2025' },
    { src: 'images/13.jpg', cat: 'surprise', title: 'Tori-gate by accident', date: '2025' },
    { src: 'images/18.jpg', cat: 'surprise', title: 'Friend or foe?', date: '2025' },
    { src: 'images/21.jpg', cat: 'surprise', title: 'Beauty in my yard', date: '2025' },
    { src: 'images/23.jpg', cat: 'surprise', title: 'Snow hats', date: '2025' },
    { src: 'images/29.jpg', cat: 'surprise', title: 'You WILL fit in!', date: '2025' },
    { src: 'images/35.jpg', cat: 'surprise', title: 'Blacksmith skills from 1920', date: '2025' },
    { src: 'images/43.jpg', cat: 'surprise', title: 'Money for nothing and chicks for free', date: '2025' },
    { src: 'images/48.jpg', cat: 'surprise', title: 'Is it you, Gilda?', date: '2025' },
    { src: 'images/50.jpg', cat: 'surprise', title: 'Red coat', date: '2025' },
    { src: 'images/99.jpg', cat: 'surprise', title: 'Cool babe', date: '2009' },
    { src: 'images/54.jpg', cat: 'surprise', title: 'Rhythm', date: '2011' },
    { src: 'images/59.jpg', cat: 'surprise', title: 'Climb!', date: '2026' },
    { src: 'images/72.jpg', cat: 'surprise', title: 'Transpfortmation', date: '2026' },
    { src: 'images/76.jpg', cat: 'surprise', title: 'Neighbour', date: '2025' },
    { src: 'images/82.jpg', cat: 'surprise', title: 'Speedster', date: '2025' },
    { src: 'images/87.jpg', cat: 'surprise', title: 'Uncle and Dad', date: '1997' },
    { src: 'images/93.jpg', cat: 'surprise', title: 'Flower lumps', date: '1996' },
    { src: 'images/107.jpg', cat: 'surprise', title: 'Legs', date: '2014' },
    { src: 'images/108.jpg', cat: 'surprise', title: 'Lamps', date: '2014' },
    { src: 'images/114.jpg', cat: 'surprise', title: 'Gang', date: '2014' },

    { src: 'images/19.jpg', cat: 'disgust', title: 'Life sucked out', date: '2025' },
    { src: 'images/27.jpg', cat: 'disgust', title: 'I told you so!', date: '2025' },
    { src: 'images/30.jpg', cat: 'disgust', title: 'Where materials meet', date: '2025' },
    { src: 'images/34.jpg', cat: 'disgust', title: 'That disgusting beautiful seaweed', date: '2025' },
    { src: 'images/37.jpg', cat: 'disgust', title: 'Spiders took over', date: '2025' },
    { src: 'images/40.jpg', cat: 'disgust', title: 'Too many elements', date: '2025' },
    { src: 'images/41.jpg', cat: 'disgust', title: 'Idiots went by', date: '2025' },
    { src: 'images/71.jpg', cat: 'disgust', title: 'Put your bicycle here in -20°C', date: '2026' },
    { src: 'images/94.jpg', cat: 'disgust', title: 'Paris', date: '2013' },
    { src: 'images/105.jpg', cat: 'disgust', title: 'Midsummers Eve', date: '2014' },
    { src: 'images/109.jpg', cat: 'disgust', title: 'Biking', date: '2014' },
    { src: 'images/112.jpg', cat: 'disgust', title: 'Winter joy', date: '2014' }
];